title: ""
description: ""

theme: minima

minima:
  skin: dark

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

# Disable automatic page title extraction
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
